### PR TITLE
Add Vortex ViBE

### PR DESCRIPTION
**Pull request by jakllsch**
Begins to address #15.

### CODE REVIEW

**Comment by jakllsch** [comment]
The T-CI build seems to always fail for GCC on MacOS...

**Comment by ChaoticConundrum** [comment]
Yea, ignore that. Travis changed something.
You should add the ViBE updater exe to this PR, And add the USB VID and PID to the `devices` map in `main.cpp`.

**Comment by jakllsch** [comment]
I don't actually have a ViBE to test against.  The USB vendor/product IDs I've used were based on the device descriptor within the firmware update package.  The bootloader product ID I've guessed, with the assumption it'll fit the pattern of being 4096 higher than the runtime PID.

**Comment by ChaoticConundrum** [comment]
Thanks!

**Pull request merged**
